version: "2"

services: 
  
  server:
    build: "./"
    ports: 
      - "8080:80"
    command: "server"

  mongodb:
    image: mongo
    container_name: mongodb

    ports:
      - "27017:27017"

  drone:
    build: "./"
    environment:
      MASTER_HOST: http://server
    command: "drone"
