version: "2"

services: 
  
  server:
    build: "./"
    environment:
      PORT: 80
      MONGODB: mongodb://mongodb/prdc-2017
    ports: 
      - "8080:80"
    command: "serve"

  mongodb:
    image: mongo
    container_name: mongodb

    ports:
      - "27017:27017"

  drone:
    build: "./"
    environment:
      MASTER_HOST: http://server
    command: "drone"
